-- =====================================================
-- Oracle：创建 BC 用户（相当于 MySQL 多库 / PG 多 schema）
-- 用法（SYSTEM 连接 PDB，例 XEPDB1）：
--   sqlplus system/xxx@//localhost:1521/XEPDB1 @00_create_users.sql
-- 生产请修改密码 KbApp_ChangeMe。
-- =====================================================

BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_user IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_document IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_file IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_statistics IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_foundation IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_intelligence IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE USER kb_agent IDENTIFIED BY KbApp_ChangeMe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1920, -955, -01920) THEN RAISE; END IF; END;
/

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_user;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_document;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_file;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_statistics;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_foundation;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_intelligence;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO kb_agent;

SELECT 'Oracle BC users ready' AS message FROM dual;
