#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""将 schema/mysql/*.sql 机械翻译为 PostgreSQL 草稿（UTF-8）。

用法: py -3 mysql_to_pg.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MYSQL_DIR = ROOT / "mysql"
PG_DIR = ROOT / "postgresql"

SKIP = {"00_create_databases.sql", "kb_intelligence.sql"}

SCHEMA_MAP = {
    "kb_user.sql": "kb_user",
    "kb_document.sql": "kb_document",
    "kb_file.sql": "kb_file",
    "kb_favorite.sql": "kb_document",
    "kb_statistics.sql": "kb_statistics",
    "kb_foundation.sql": "kb_foundation",
    "kb_agent.sql": "kb_agent",
    "kb_notification_template.sql": "kb_foundation",
}


def strip_backticks(s: str) -> str:
    return s.replace("`", "")


def convert_column_line(line: str) -> str | None:
    """转换 CREATE TABLE 内一行；返回 None 表示删除该行（KEY 已提取）。"""
    raw = line.rstrip()
    stripped = raw.strip()
    if not stripped:
        return raw

    # 提取 KEY / INDEX 由外层处理，这里若遇到则返回特殊标记
    return raw


def transform_types(s: str) -> str:
    s = re.sub(r"\bTINYINT\s*\(\s*1\s*\)", "SMALLINT", s, flags=re.I)
    s = re.sub(r"\bTINYINT\b", "SMALLINT", s, flags=re.I)
    s = re.sub(r"\bMEDIUMTEXT\b", "TEXT", s, flags=re.I)
    s = re.sub(r"\bLONGTEXT\b", "TEXT", s, flags=re.I)
    s = re.sub(r"\bDATETIME\b", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\bDOUBLE\b", "DOUBLE PRECISION", s, flags=re.I)
    s = re.sub(r"\bJSON\b", "JSONB", s, flags=re.I)
    s = re.sub(
        r"\bBIGINT\s+NOT\s+NULL\s+AUTO_INCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\bBIGINT\s+AUTO_INCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )
    s = re.sub(r"\bAUTO_INCREMENT\b", "", s, flags=re.I)
    s = re.sub(r"\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP", "", s, flags=re.I)
    s = re.sub(r"\s+COMMENT\s+'[^']*'", "", s)
    # 注意：不要全局去掉 (digits)，否则会把 VARCHAR(255) 变成 VARCHAR
    return s


def convert_create_table(block: str) -> str:
    """block 以 CREATE TABLE 开头，含完整语句到分号。"""
    block = strip_backticks(block)
    m = re.match(
        r"(?is)^(CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?)(\w+)\s*\((.*)\)\s*(.*?);?\s*$",
        block.strip(),
    )
    if not m:
        # 兜底：去引擎后返回
        s = transform_types(block)
        s = re.sub(r"\)\s*ENGINE=InnoDB[^;]*", ")", s, flags=re.I)
        return s if s.rstrip().endswith(";") else s.rstrip() + ";\n"

    prefix, table, inner, _tail = m.group(1), m.group(2), m.group(3), m.group(4)
    indexes: list[str] = []
    col_parts: list[str] = []

    # 按顶层逗号分割（忽略括号内逗号）
    pieces: list[str] = []
    buf = []
    depth = 0
    for ch in inner:
        if ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth -= 1
            buf.append(ch)
        elif ch == "," and depth == 0:
            pieces.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    if buf:
        pieces.append("".join(buf).strip())

    for piece in pieces:
        if not piece:
            continue
        uk = re.match(r"(?is)^UNIQUE\s+KEY\s+(\w+)\s*\((.+)\)$", piece)
        if uk:
            cols = re.sub(r"(\w+)\(\d+\)", r"\1", uk.group(2))
            col_parts.append(f"CONSTRAINT {uk.group(1)} UNIQUE ({cols})")
            continue
        pk = re.match(r"(?is)^PRIMARY\s+KEY\s*\((.+)\)$", piece)
        if pk:
            col_parts.append(f"PRIMARY KEY ({pk.group(1)})")
            continue
        key = re.match(r"(?is)^(?:KEY|INDEX)\s+(\w+)\s*\((.+)\)$", piece)
        if key:
            cols = re.sub(r"(\w+)\(\d+\)", r"\1", key.group(2))
            indexes.append(
                f"CREATE INDEX IF NOT EXISTS {key.group(1)} ON {table} ({cols});"
            )
            continue
        # 普通列 / 约束
        col = transform_types(piece)
        col = col.strip().rstrip(",")
        if col:
            col_parts.append(col)

    cols_sql = ",\n  ".join(col_parts)
    out = f"{prefix}{table} (\n  {cols_sql}\n);\n"
    if indexes:
        out += "\n".join(indexes) + "\n"
    return out


def convert_file(text: str, schema: str) -> str:
    text = re.sub(r"(?im)^SET\s+NAMES\s+utf8mb4\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^SET\s+FOREIGN_KEY_CHECKS\s*=\s*\d+\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^USE\s+`?\w+`?\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^SHOW\s+TABLES\s*;\s*\n?", "", text)
    text = strip_backticks(text)
    text = re.sub(
        r"(?im)^DROP\s+TABLE\s+IF\s+EXISTS\s+(\w+)\s*;",
        r"DROP TABLE IF EXISTS \1 CASCADE;",
        text,
    )

    header = (
        f"-- =====================================================\n"
        f"-- PostgreSQL 翻译稿（自 mysql/ 机械转换，需人工验证）\n"
        f"-- schema: {schema}\n"
        f"-- =====================================================\n\n"
        f"SET search_path TO {schema};\n\n"
    )

    out: list[str] = [header]
    pos = 0
    create_re = re.compile(r"(?is)CREATE\s+TABLE\b")

    while True:
        m = create_re.search(text, pos)
        if not m:
            rest = text[pos:].strip()
            if rest:
                rest = transform_types(rest)
                # INSERT 多行 VALUES 逗号保留
                out.append(rest)
                if not rest.endswith("\n"):
                    out.append("\n")
            break
        # preamble
        pre = text[pos : m.start()].strip()
        if pre:
            out.append(pre + "\n\n")
        # find matching end: first ); that closes CREATE, allowing ENGINE clause
        start = m.start()
        # find opening paren after TABLE name
        paren = text.find("(", m.end())
        if paren < 0:
            out.append(text[start:])
            break
        depth = 0
        i = paren
        end = -1
        while i < len(text):
            ch = text[i]
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth == 0:
                    # consume optional ENGINE... until ;
                    j = i + 1
                    while j < len(text) and text[j] != ";":
                        j += 1
                    end = j + 1 if j < len(text) else i + 1
                    break
            i += 1
        if end < 0:
            out.append(text[start:])
            break
        block = text[start:end]
        out.append(convert_create_table(block))
        out.append("\n")
        pos = end

    return "".join(out).rstrip() + "\n"


def main() -> int:
    PG_DIR.mkdir(parents=True, exist_ok=True)
    for path in sorted(MYSQL_DIR.glob("*.sql")):
        if path.name in SKIP:
            print(f"skip {path.name}")
            continue
        schema = SCHEMA_MAP.get(path.name)
        if not schema:
            print(f"no schema map for {path.name}, skip")
            continue
        out = convert_file(path.read_text(encoding="utf-8"), schema)
        dest = PG_DIR / path.name
        dest.write_text(out, encoding="utf-8")
        print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
