#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""将 schema/mysql/*.sql 机械翻译为 Oracle 草稿（UTF-8）。

用法: py -3 mysql_to_oracle.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MYSQL_DIR = ROOT / "mysql"
ORA_DIR = ROOT / "oracle"

SKIP = {"00_create_databases.sql"}

SCHEMA_MAP = {
    "kb_user.sql": "kb_user",
    "kb_document.sql": "kb_document",
    "kb_file.sql": "kb_file",
    "kb_favorite.sql": "kb_document",
    "kb_statistics.sql": "kb_statistics",
    "kb_foundation.sql": "kb_foundation",
    "kb_agent.sql": "kb_agent",
    "kb_intelligence.sql": "kb_intelligence",
    "kb_notification_template.sql": "kb_foundation",
}


def strip_backticks(s: str) -> str:
    """去掉 MySQL 反引号。"""
    return s.replace("`", "")


def drop_plsql(schema: str, table: str) -> str:
    """生成忽略 ORA-00942 的 DROP TABLE（限定 schema）。"""
    fq = f"{schema}.{table}"
    return (
        f"BEGIN\n"
        f"  EXECUTE IMMEDIATE 'DROP TABLE {fq} CASCADE CONSTRAINTS';\n"
        f"EXCEPTION\n"
        f"  WHEN OTHERS THEN\n"
        f"    IF SQLCODE != -942 THEN RAISE; END IF;\n"
        f"END;\n"
        f"/\n"
    )


RESERVED_COLS = {
    "level",
    "number",
    "date",
    "order",
    "size",
    "file",
    "mode",
    "uid",
    "user",
    "comment",
    "share",
    "access",
    "raw",
    "type",
}


def quote_col_name(name: str) -> str:
    """Oracle 保留字列名加双引号。"""
    if name.lower() in RESERVED_COLS:
        return f'"{name.lower()}"'
    return name


def transform_types(s: str) -> str:
    """列类型与默认值映射到 Oracle。"""
    # 先处理自增，避免 BIGINT 被提前替换后漏匹配
    s = re.sub(
        r"\bBIGINT\s+NOT\s+NULL\s+AUTO_INCREMENT\b",
        "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\bBIGINT\s+AUTO_INCREMENT\b",
        "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )
    s = re.sub(r"\bTINYINT\s*\(\s*1\s*\)", "NUMBER(3)", s, flags=re.I)
    s = re.sub(r"\bTINYINT\b", "NUMBER(3)", s, flags=re.I)
    s = re.sub(r"\bSMALLINT\b", "NUMBER(5)", s, flags=re.I)
    s = re.sub(r"\bBIGINT\b", "NUMBER(19)", s, flags=re.I)
    s = re.sub(r"\bINT\b", "NUMBER(10)", s, flags=re.I)
    s = re.sub(r"\bINTEGER\b", "NUMBER(10)", s, flags=re.I)
    s = re.sub(r"\bDOUBLE\b", "BINARY_DOUBLE", s, flags=re.I)
    s = re.sub(r"\bFLOAT\b", "BINARY_FLOAT", s, flags=re.I)
    s = re.sub(r"\bMEDIUMTEXT\b", "CLOB", s, flags=re.I)
    s = re.sub(r"\bLONGTEXT\b", "CLOB", s, flags=re.I)
    s = re.sub(r"\bTEXT\b", "CLOB", s, flags=re.I)
    s = re.sub(r"\bJSON\b", "CLOB", s, flags=re.I)
    s = re.sub(r"\bVARCHAR\s*\(", "VARCHAR2(", s, flags=re.I)
    s = re.sub(r"\bDATETIME\b", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\bAUTO_INCREMENT\b", "", s, flags=re.I)
    s = re.sub(r"\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP", "", s, flags=re.I)
    s = re.sub(r"\bDEFAULT\s+CURRENT_TIMESTAMP\b", "DEFAULT SYSTIMESTAMP", s, flags=re.I)
    s = re.sub(r"\s+DEFAULT\s+NULL\b", "", s, flags=re.I)
    s = re.sub(r"\s+COMMENT\s+'[^']*'", "", s)
    s = re.sub(r"\s+COMMENT\s+\"[^\"]*\"", "", s)
    # Oracle：DEFAULT 必须在 NOT NULL 之前
    s = re.sub(
        r"(\b(?:NUMBER\(\d+\)|VARCHAR2\(\d+\)|TIMESTAMP|CLOB|BINARY_DOUBLE|BINARY_FLOAT))"
        r"\s+NOT\s+NULL\s+DEFAULT\s+('[^']*'|[^\s,]+)",
        r"\1 DEFAULT \2 NOT NULL",
        s,
        flags=re.I,
    )
    return s


def convert_create_table(block: str, schema: str) -> str:
    """转换单条 CREATE TABLE，抽出索引为独立语句。"""
    block = strip_backticks(block)
    # 去掉 IF NOT EXISTS
    block = re.sub(r"(?i)CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+", "CREATE TABLE ", block)
    m = re.match(
        r"(?is)^(CREATE\s+TABLE\s+)(\w+)\s*\((.*)\)\s*(.*?);?\s*$",
        block.strip(),
    )
    if not m:
        s = transform_types(block)
        s = re.sub(r"\)\s*ENGINE=InnoDB[^;]*", ")", s, flags=re.I)
        return s if s.rstrip().endswith(";") else s.rstrip() + ";\n"

    prefix, table, inner, _tail = m.group(1), m.group(2), m.group(3), m.group(4)
    fq = f"{schema}.{table}"
    indexes: list[str] = []
    col_parts: list[str] = []

    pieces: list[str] = []
    buf: list[str] = []
    depth = 0
    for ch in inner:
        if ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth -= 1
            buf.append(ch)
        elif ch == "," and depth == 0:
            pieces.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    if buf:
        pieces.append("".join(buf).strip())

    for piece in pieces:
        if not piece:
            continue
        uk = re.match(r"(?is)^UNIQUE\s+KEY\s+(\w+)\s*\((.+)\)$", piece)
        if uk:
            cols = re.sub(r"(\w+)\(\d+\)", r"\1", uk.group(2))
            col_parts.append(f"CONSTRAINT {uk.group(1)} UNIQUE ({cols})")
            continue
        uk2 = re.match(r"(?is)^UNIQUE\s+INDEX\s+(\w+)\s*\((.+)\)$", piece)
        if uk2:
            cols = re.sub(r"(\w+)\(\d+\)", r"\1", uk2.group(2))
            col_parts.append(f"CONSTRAINT {uk2.group(1)} UNIQUE ({cols})")
            continue
        pk = re.match(r"(?is)^PRIMARY\s+KEY\s*\((.+)\)$", piece)
        if pk:
            col_parts.append(f"PRIMARY KEY ({pk.group(1)})")
            continue
        if re.search(r"(?i)\bPRIMARY\s+KEY\b", piece) and not piece.upper().startswith("PRIMARY"):
            col = transform_types(piece)
            col = re.sub(r"(?i)\bPRIMARY\s+KEY\b", "", col).strip().rstrip(",")
            if col:
                col_parts.append(col)
                cm = re.match(r"(\w+)", col)
                if cm:
                    col_parts.append(f"PRIMARY KEY ({cm.group(1)})")
            continue
        key = re.match(r"(?is)^(?:KEY|INDEX)\s+(\w+)\s*\((.+)\)$", piece)
        if key:
            cols = re.sub(r"(\w+)\(\d+\)", r"\1", key.group(2))
            idx_name = f"idx_{table}_{key.group(1)}"
            if len(idx_name) > 128:
                idx_name = idx_name[:128]
            indexes.append(f"CREATE INDEX {idx_name} ON {fq} ({cols});")
            continue
        ft = re.match(r"(?is)^FULLTEXT\s+(?:KEY|INDEX)\s+(\w+)\s*\((.+)\)$", piece)
        if ft:
            indexes.append(
                f"-- SKIPPED FULLTEXT {ft.group(1)} ON {fq} ({ft.group(2)}); "
                f"-- use Oracle Text if needed"
            )
            continue
        col = transform_types(piece)
        col = col.strip().rstrip(",")
        if col:
            cm = re.match(r"^(\w+)(\s+.*)$", col, re.S)
            if cm:
                col = quote_col_name(cm.group(1)) + cm.group(2)
            col_parts.append(col)

    cleaned: list[str] = []
    seen_pk = False
    for c in col_parts:
        if c.upper().startswith("PRIMARY KEY"):
            if seen_pk:
                continue
            seen_pk = True
        cleaned.append(c)

    cols_sql = ",\n  ".join(cleaned)
    out = f"{prefix}{fq} (\n  {cols_sql}\n);\n"
    if indexes:
        out += "\n".join(indexes) + "\n"
    return out


def convert_file(text: str, schema: str) -> str:
    """整文件转换。"""
    text = re.sub(r"(?im)^SET\s+NAMES\s+utf8mb4\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^SET\s+FOREIGN_KEY_CHECKS\s*=\s*\d+\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^USE\s+`?\w+`?\s*;\s*\n?", "", text)
    text = re.sub(r"(?im)^SHOW\s+TABLES\s*;\s*\n?", "", text)
    text = strip_backticks(text)

    # DROP TABLE IF EXISTS → PL/SQL
    def _repl_drop(m: re.Match[str]) -> str:
        return drop_plsql(schema, m.group(1))

    text = re.sub(
        r"(?im)^DROP\s+TABLE\s+IF\s+EXISTS\s+(\w+)\s*;\s*",
        _repl_drop,
        text,
    )

    header = (
        f"-- =====================================================\n"
        f"-- Oracle 翻译稿（自 mysql/ 机械转换，需人工验证）\n"
        f"-- schema/user: {schema}\n"
        f"-- 以 SYSTEM 装载时使用限定名 {schema}.table\n"
        f"-- =====================================================\n\n"
    )

    out: list[str] = [header]
    pos = 0
    create_re = re.compile(r"(?is)CREATE\s+TABLE\b")

    while True:
        m = create_re.search(text, pos)
        if not m:
            rest = text[pos:].strip()
            if rest:
                rest = transform_types(rest)
                rest = re.sub(r"(?i)\bNOW\(\)", "SYSTIMESTAMP", rest)
                rest = re.sub(
                    rf"(?i)\bINSERT\s+INTO\s+(?!{schema}\.)(\w+)",
                    rf"INSERT INTO {schema}.\1",
                    rest,
                )
                out.append(rest)
                if not rest.endswith("\n"):
                    out.append("\n")
            break
        pre = text[pos : m.start()].strip()
        if pre:
            # 已转换的 DROP 块等
            pre = transform_types(pre)
            out.append(pre + "\n\n")
        start = m.start()
        paren = text.find("(", m.end())
        if paren < 0:
            out.append(text[start:])
            break
        depth = 0
        i = paren
        end = -1
        while i < len(text):
            ch = text[i]
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth == 0:
                    j = i + 1
                    while j < len(text) and text[j] != ";":
                        j += 1
                    end = j + 1 if j < len(text) else i + 1
                    break
            i += 1
        if end < 0:
            out.append(text[start:])
            break
        block = text[start:end]
        out.append(convert_create_table(block, schema))
        out.append("\n")
        pos = end

    return "".join(out).rstrip() + "\n"


def main() -> int:
    """生成 oracle/ 下各 BC SQL。"""
    ORA_DIR.mkdir(parents=True, exist_ok=True)
    for path in sorted(MYSQL_DIR.glob("*.sql")):
        if path.name in SKIP:
            print(f"skip {path.name}")
            continue
        schema = SCHEMA_MAP.get(path.name)
        if not schema:
            print(f"no schema map for {path.name}, skip")
            continue
        out = convert_file(path.read_text(encoding="utf-8"), schema)
        dest = ORA_DIR / path.name
        dest.write_text(out, encoding="utf-8")
        print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
